### ISSUE TITLE
TypeError: 'filter' object is not subscriptable

### ISSUE THREAD

**Issue by acgtyrant** [fonttools/pyclipper#19]
I try to install this in Arch Linux, failed.

This is the part log:

```
Development mode: Compiling Cython modules from .pyx sources.                                                                           
Traceback (most recent call last):                                                                                                      
  File "setup.py", line 96, in <module>                                                                                                 
    cmdclass=cmdclass,                                                                                                                  
  File "/usr/lib/python3.6/site-packages/setuptools/__init__.py", line 129, in setup                                                    
    return distutils.core.setup(**attrs)                                                                                                
  File "/usr/lib/python3.6/distutils/core.py", line 108, in setup                                                                       
    _setup_distribution = dist = klass(attrs)                                                                                           
  File "/usr/lib/python3.6/site-packages/setuptools/dist.py", line 370, in __init__                                                     
    k: v for k, v in attrs.items()                                                                                                      
  File "/usr/lib/python3.6/distutils/dist.py", line 281, in __init__                                                                    
    self.finalize_options()
  File "/usr/lib/python3.6/site-packages/setuptools/dist.py", line 529, in finalize_options                                            
    ep.load()(self, ep.name, value)
  File "/home/acgtyrant/.cache/aurman/python-pyclipper/src/pyclipper-1.1.0/.eggs/setuptools_scm-3.0.2-py3.6.egg/setuptools_scm/integration.py", line 23, in version_keyword
    dist.metadata.version = get_version(**value)
  File "/home/acgtyrant/.cache/aurman/python-pyclipper/src/pyclipper-1.1.0/.eggs/setuptools_scm-3.0.2-py3.6.egg/setuptools_scm/__init__.py", line 135, in get_version
    parsed_version = _do_parse(config)
  File "/home/acgtyrant/.cache/aurman/python-pyclipper/src/pyclipper-1.1.0/.eggs/setuptools_scm-3.0.2-py3.6.egg/setuptools_scm/__init__.py", line 88, in _do_parse
    config, "setuptools_scm.parse_scm"
  File "/home/acgtyrant/.cache/aurman/python-pyclipper/src/pyclipper-1.1.0/.eggs/setuptools_scm-3.0.2-py3.6.egg/setuptools_scm/__init__.py", line 45, in _version_from_entrypoint
    version = _call_entrypoint_fn(config, ep.load())
  File "/home/acgtyrant/.cache/aurman/python-pyclipper/src/pyclipper-1.1.0/.eggs/setuptools_scm-3.0.2-py3.6.egg/setuptools_scm/__init__.py", line 40, in _call_entrypoint_fn
    return fn(config.absolute_root)
  File "/home/acgtyrant/.cache/aurman/python-pyclipper/src/pyclipper-1.1.0/.eggs/setuptools_scm_git_archive-1.0-py3.6.egg/setuptools_scm_git_archive/__init__.py", line 21, in parse
    return archival_to_version(data)
  File "/home/acgtyrant/.cache/aurman/python-pyclipper/src/pyclipper-1.1.0/.eggs/setuptools_scm_git_archive-1.0-py3.6.egg/setuptools_scm_git_archive/__init__.py", line 15, in archival_to_version
    return meta(versions[0])
TypeError: 'filter' object is not subscriptable
==> ERROR: A failure occurred in build().
    Aborting...
2018-07-27 17:35:44,380 - wrappers - makepkg - ERROR - makepkg query ['makepkg', '-cf', '--noconfirm'] failed in directory /home/acgtyrant/.cache/aurman/python-pyclipper
```

**Comment by anthrotype** [comment]
thanks, I decided to simply drop setuptools_scm_git_archive. I don't think it adds any value, if one needs the source distribution, one can either clone the repo or download the sdist package from PyPI.

**Comment by acgtyrant** [comment]
I confirm that I can install from source now.
