### ISSUE TITLE
1.1.0.post2 fails to build: LookupError: setuptools-scm was unable to detect version for '/var/tmp/portage/dev-python/pyclipper-1.1.0_p2/work/pyclipper-1.1.0.post2'.

### ISSUE THREAD

**Issue by pacho2** [fonttools/pyclipper#24]
I get this error:
python2.7 setup.py build
Development mode: Compiling Cython modules from .pyx sources.
Traceback (most recent call last):
  File "setup.py", line 97, in <module>
    cmdclass=cmdclass,
  File "/usr/lib64/python2.7/site-packages/setuptools/__init__.py", line 143, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib64/python2.7/distutils/core.py", line 111, in setup
    _setup_distribution = dist = klass(attrs)
  File "/usr/lib64/python2.7/site-packages/setuptools/dist.py", line 442, in __init__
    k: v for k, v in attrs.items()
  File "/usr/lib64/python2.7/distutils/dist.py", line 287, in __init__
    self.finalize_options()
  File "/usr/lib64/python2.7/site-packages/setuptools/dist.py", line 601, in finalize_options
    ep.load()(self, ep.name, value)
  File "/usr/lib64/python2.7/site-packages/setuptools_scm/integration.py", line 23, in version_keyword
    dist.metadata.version = get_version(**value)
  File "/usr/lib64/python2.7/site-packages/setuptools_scm/__init__.py", line 144, in get_version
    parsed_version = _do_parse(config)
  File "/usr/lib64/python2.7/site-packages/setuptools_scm/__init__.py", line 111, in _do_parse
    "use git+https://github.com/user/proj.git#egg=proj" % config.absolute_root
LookupError: setuptools-scm was unable to detect version for '/var/tmp/portage/dev-python/pyclipper-1.1.0_p2/work/pyclipper-1.1.0.post2'.

Make sure you're either building from a fully intact git repository or PyPI tarballs. Most other sources (such as GitHub's tarballs, a git checkout without the .git folder) don't contain the necessary metadata and will not work.

Thanks

**Comment by jayvdb** [comment]
This might be related to https://github.com/pypa/setuptools_scm/issues/357
